#配置dubbo
dubbo:
  scan:
    base-packages: org.xujiaqi
  application:
    name: ${spring.application.name}
  protocol: #协议
    name: dubbo
    port: 20880
  registry: #注册信息,原值为nacos://localhost:8848/。这个是dubbo和spring-boot和nacos整合，但是现在要把他放到注册中心去，不然会和原有服务注册冲突
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ${spring.application.name}
#    use-as-config-center: false

#配置mapper
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml



