server:
  port: 8001

#
spring:
  application:
    name: spring-cloud-alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #,localhost:1111
#    sentinel:
#      transport:
#        dashboard: localhost:8080


#配置dubbo
dubbo:
  application:
    name: provider8001
#协议
  protocol:
    name: dubbo
    port: 20880
    serialization: fastjson2
  #dubbo.registry.address=nacos://localhost:8848/
#注册中心
  registry:
    address: nacos://localhost:8848/
    use-as-config-center: false




