dubbo:
  scan:
    base-packages: org.xujiaqi
  protocol:
    name: dubbo
    #自动分配端口
    port: -1
  registry:
    #如果是使用springcloud的注册中心,就直接填这个就可以了(固定值)
    address: spring-cloud://localhost
  application:
    name: ${spring.application.name}
  cloud:
    subscribed-services: spring-cloud-alibaba-provider

logging:
  level:
    org.xujiaqi: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

